# Generated by Django 5.2.12 on 2026-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Guruh nomi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.CharField(max_length=200, verbose_name="O'qituvchi"),
        ),
    ]
