# Generated by Django 5.2.12 on 2026-04-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Talaba'), ('admin', 'Administrator')], default='student', max_length=10, verbose_name='Rol'),
        ),
    ]
