# Generated by Django 5.2.12 on 2026-04-09 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_examsession_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_control', to='groups.group')),
            ],
        ),
    ]
