# Generated by Django 5.2.12 on 2026-04-09 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_examcontrol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ochiq parol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin paroli',
                'verbose_name_plural': 'Admin parollari',
            },
        ),
    ]
