# Generated by Django 5.2.12 on 2026-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_adminpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL (YouTube)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='rules_videos/', verbose_name='Video fayl')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='rules_images/', verbose_name='Rasm 1')),
                ('image1_title', models.CharField(blank=True, default='Imtihon tartibi', max_length=200, verbose_name='Rasm 1 sarlavhasi')),
                ('image1_description', models.TextField(blank=True, default="Imtihon vaqtida nimalarga e'tibor berish kerak", verbose_name='Rasm 1 izohi')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rules_images/', verbose_name='Rasm 2')),
                ('image2_title', models.CharField(blank=True, default='Baholash mezonlari', max_length=200, verbose_name='Rasm 2 sarlavhasi')),
                ('image2_description', models.TextField(blank=True, default='Qanday qilib yuqori ball olish mumkin', verbose_name='Rasm 2 izohi')),
                ('rules_text', models.TextField(default="1. Telefon va qurilmalardan foydalanish QAT'IY MAN ETILADI\n2. Belgilangan vaqtda topshirish shart\n3. Ko'chirish qat'iyan man etiladi\n4. Texnik muammoda o'qituvchiga murojaat qiling\n5. Natijalar tekshiruvdan keyin e'lon qilinadi", verbose_name='Qoidalar matni')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qonun va qoidalar',
                'verbose_name_plural': 'Qonun va qoidalar',
            },
        ),
    ]
