# Generated by Django 5.2.12 on 2026-04-18 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_quizquestion_quizsession_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz savoli', 'verbose_name_plural': 'Quiz savollari'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': 'Quiz natijasi', 'verbose_name_plural': 'Quiz natijalari'},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={'verbose_name': 'Quiz sessiyasi', 'verbose_name_plural': 'Quiz sessiyalari'},
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='groups.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='Javoblar'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0, verbose_name='Jami savollar'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('student', 'quiz_session')},
        ),
    ]
