# Generated by Django 5.2.12 on 2026-04-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_quizquestion_options_alter_quizresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Test savoli', 'verbose_name_plural': 'Test savollari'},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(default=1, max_length=500, verbose_name='A varianti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(default=1, max_length=500, verbose_name='B varianti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, verbose_name='C varianti'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, verbose_name='D varianti'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='groups.group'),
        ),
    ]
