# Generated by Django 5.2.12 on 2026-04-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_alter_quizquestion_options_quizquestion_option_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz savoli', 'verbose_name_plural': 'Quiz savollari'},
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_d',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(max_length=255, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='groups.group', verbose_name='Guruh'),
        ),
    ]
