# Generated by Django 6.0.4 on 2026-04-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['category__name', 'id'], 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='group',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='groups.category', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_categories', to='groups.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_categories', to='groups.group')),
            ],
            options={
                'verbose_name': 'Guruh kategoriyasi',
                'verbose_name_plural': 'Guruh kategoriyalari',
                'unique_together': {('group', 'category')},
            },
        ),
    ]
