# Generated by Django 6.0.4 on 2026-04-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_category_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(default=10, verbose_name='Savollar soni')),
                ('random_order', models.BooleanField(default=True, verbose_name='Random tartib')),
                ('show_correct_answer', models.BooleanField(default=False, verbose_name="To'g'ri javobni ko'rsatish")),
                ('time_limit', models.IntegerField(default=0, help_text='0 - cheksiz', verbose_name='Vaqt limiti (daqiqa)')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_config', to='groups.group')),
            ],
            options={
                'verbose_name': 'Imtihon sozlamalari',
                'verbose_name_plural': 'Imtihon sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='UserExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_questions', models.JSONField(default=list, verbose_name="Tanlangan savol ID'lari")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='groups.quizsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='groups.student')),
            ],
            options={
                'verbose_name': 'Imtihon urinishi',
                'verbose_name_plural': 'Imtihon urinishlari',
            },
        ),
    ]
