# Generated by Django 6.0.4 on 2026-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_groupexamconfig_userexamattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupexamconfig',
            options={'verbose_name': 'Guruh imtihon sozlamasi', 'verbose_name_plural': 'Guruh imtihon sozlamalari'},
        ),
        migrations.RemoveField(
            model_name='groupexamconfig',
            name='question_count',
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='max_attempts',
            field=models.IntegerField(default=1, verbose_name='Maksimal urinishlar'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='questions_per_student',
            field=models.IntegerField(default=10, verbose_name='Har bir talabaga savollar soni'),
        ),
        migrations.AddField(
            model_name='groupexamconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
