# Generated by Django 6.0.4 on 2026-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_alter_groupexamconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupexamconfig',
            options={'verbose_name': 'Imtihon sozlamasi', 'verbose_name_plural': 'Imtihon sozlamalari'},
        ),
        migrations.AlterField(
            model_name='adminpassword',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupexamconfig',
            name='questions_per_student',
            field=models.IntegerField(default=5, verbose_name='Har bir talabaga savollar soni'),
        ),
        migrations.AlterField(
            model_name='groupexamconfig',
            name='time_limit',
            field=models.IntegerField(default=0, verbose_name='Vaqt limiti (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rules_images/'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image1_description',
            field=models.TextField(blank=True, default="Imtihon vaqtida nimalarga e'tibor berish kerak"),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image1_title',
            field=models.CharField(blank=True, default='Imtihon tartibi', max_length=200),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rules_images/'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image2_description',
            field=models.TextField(blank=True, default='Qanday qilib yuqori ball olish mumkin'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image2_title',
            field=models.CharField(blank=True, default='Baholash mezonlari', max_length=200),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rules_text',
            field=models.TextField(default="1. Telefon va qurilmalardan foydalanish QAT'IY MAN ETILADI\n2. Belgilangan vaqtda topshirish shart\n3. Ko'chirish qat'iyan man etiladi\n4. Texnik muammoda o'qituvchiga murojaat qiling\n5. Natijalar tekshiruvdan keyin e'lon qilinadi"),
        ),
        migrations.AlterField(
            model_name='rules',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='rules_videos/'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userexamattempt',
            name='selected_questions',
            field=models.JSONField(default=list, verbose_name='Tanlangan savollar'),
        ),
    ]
