# Generated by Django 6.0.4 on 2026-04-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_alter_groupexamconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcontrol',
            options={'verbose_name': 'Imtihon boshqaruvi', 'verbose_name_plural': 'Imtihon boshqaruvlari'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Quiz natijasi', 'verbose_name_plural': 'Quiz natijalari'},
        ),
        migrations.AlterModelOptions(
            name='userexamattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Imtihon urinishi', 'verbose_name_plural': 'Imtihon urinishlari'},
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='attempt_number',
            field=models.IntegerField(default=1, verbose_name='Urinish raqami'),
        ),
        migrations.AddField(
            model_name='userexamattempt',
            name='attempt_number',
            field=models.IntegerField(default=1, verbose_name='Urinish raqami'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rules_images/', verbose_name='Rasm 1'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image1_description',
            field=models.TextField(blank=True, default="Imtihon vaqtida nimalarga e'tibor berish kerak", verbose_name='Rasm 1 tavsifi'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image1_title',
            field=models.CharField(blank=True, default='Imtihon tartibi', max_length=200, verbose_name='Rasm 1 sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rules_images/', verbose_name='Rasm 2'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image2_description',
            field=models.TextField(blank=True, default='Qanday qilib yuqori ball olish mumkin', verbose_name='Rasm 2 tavsifi'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='image2_title',
            field=models.CharField(blank=True, default='Baholash mezonlari', max_length=200, verbose_name='Rasm 2 sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rules_text',
            field=models.TextField(default="1. Telefon va qurilmalardan foydalanish QAT'IY MAN ETILADI\n2. Belgilangan vaqtda topshirish shart\n3. Ko'chirish qat'iyan man etiladi\n4. Texnik muammoda o'qituvchiga murojaat qiling\n5. Natijalar tekshiruvdan keyin e'lon qilinadi", verbose_name='Qoidalar matni'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='rules_videos/', verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL'),
        ),
    ]
