# Generated by Django 6.0.4 on 2026-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_alter_examcontrol_options_alter_quizresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correct_sentence',
            field=models.TextField(blank=True, help_text='Masalan: I go to school', null=True, verbose_name="To'g'ri gap (sentence arrangement)"),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', 'Bosh joy toldirish'), ('sentence_arrangement', "So'zlarni tartibga solish"), ('multiple_choice', 'Test varianti'), ('true_false', "To'g'ri/Noto'g'ri")], default='fill_blank', max_length=30, verbose_name='Savol turi'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='scrambled_words',
            field=models.TextField(blank=True, help_text='Masalan: he / go / school / I / to', null=True, verbose_name="Chalkashtirilgan so'zlar (sentence arrangement)"),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Savol matni'),
        ),
    ]
